version: '3.8'
services:
  app:
    image: weather:latest
    container_name: ${COMPOSE_PROJECT_NAME?}
    restart: always

    environment:
      APP_ENV: ${APP_ENV?}
      APP_URL: ${APP_URL?}

    networks:
      - net-frontend

networks:
  net-frontend:
    driver: bridge
